import { IPhoto } from "../interfaces/photo.interface";

export const photodb: IPhoto[] = [
	{
		path: "/src/db/photos/photo1.jpeg",
		camera: "Praktica L",
		film: "Hitchcock 250",
		lens: "Helios-44-2",
		location: "Arkhangelsk, Malye Korely",
	},
	{
		path: "/src/db/photos/photo2.jpeg",
		camera: "Praktica L",
		film: "Hitchcock 250",
		lens: "Helios-44-2",
		location: "Arkhangelsk, Malye Korely",
	},
	{
		path: "/src/db/photos/photo3.jpeg",
		camera: "Praktica L",
		film: "Hitchcock 250",
		lens: "Helios-44-2",
		location: "Arkhangelsk, Malye Korely",
	},
	{
		path: "/src/db/photos/photo4.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Russky Island",
	},
	{
		path: "/src/db/photos/photo5.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Russky Island",
	},
	{
		path: "/src/db/photos/photo6.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Tokarevsky lighthouse",
	},
	{
		path: "/src/db/photos/photo7.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Glass Bay",
	},
	{
		path: "/src/db/photos/photo8.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Russky Island",
	},
	{
		path: "/src/db/photos/photo9.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok, Russky Island",
	},
	{
		path: "/src/db/photos/photo10.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Arkhangelsk",
	},
	{
		path: "/src/db/photos/photo11.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Arkhangelsk",
	},
	{
		path: "/src/db/photos/photo12.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Arkhangelsk",
	},
	{
		path: "/src/db/photos/photo13.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Arkhangelsk",
	},
	{
		path: "/src/db/photos/photo14.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Arkhangelsk",
	},
	{
		path: "/src/db/photos/photo15.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
	{
		path: "/src/db/photos/photo16.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
	{
		path: "/src/db/photos/photo17.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
	{
		path: "/src/db/photos/photo18.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
	{
		path: "/src/db/photos/photo19.jpeg",
		camera: "Praktica L",
		film: "Hitchcock 250",
		lens: "Helios-44-2",
		location: "Arkhangelsk, Malye Korely",
	},
	{
		path: "/src/db/photos/photo20.jpeg",
		camera: "Praktica L",
		film: "Hitchcock 250",
		lens: "Helios-44-2",
		location: "Arkhangelsk, Malye Korely",
	},
	{
		path: "/src/db/photos/photo21.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok",
	},
	{
		path: "/src/db/photos/photo22.jpeg",
		camera: "Praktica L",
		film: "Kodak Vision 500",
		lens: "Helios-44-2",
		location: "Vladivostok",
	},
	{
		path: "/src/db/photos/photo23.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
	{
		path: "/src/db/photos/photo24.jpeg",
		camera: "Praktica L",
		film: "Tasma 100",
		lens: "Helios-44-2",
		location: "Saint Petersburg",
	},
];
