import { IPhoto } from '../interfaces/photo.interface';

export const photodb: IPhoto[] = [
	{
		id: 1,
		path: '/src/db/photos/photo1.jpg',
		camera: 'Praktica L',
		plenka: 'Hitchcock 250',
		location: 'Arkhangelsk, Museum-Reserve Malye Korely',
	},
	{
		id: 2,
		path: '/src/db/photos/photo2.jpg',
		camera: 'Praktica L',
		plenka: 'Hitchcock 250',
		location: 'Arkhangelsk, Museum-Reserve Malye Korely',
	},
	{
		id: 3,
		path: '/src/db/photos/photo3.jpg',
		camera: 'Praktica L',
		plenka: 'Hitchcock 250',
		location: 'Arkhangelsk, Museum-Reserve Malye Korely',
	},
	{
		id: 4,
		path: '/src/db/photos/photo4.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Russky Island',
	},
	{
		id: 5,
		path: '/src/db/photos/photo5.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Russky Island',
	},
	{
		id: 6,
		path: '/src/db/photos/photo6.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Tokarevsky lighthouse',
	},
	{
		id: 7,
		path: '/src/db/photos/photo7.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Glass Bay',
	},
	{
		id: 8,
		path: '/src/db/photos/photo8.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Russky Island',
	},
	{
		id: 9,
		path: '/src/db/photos/photo9.jpg',
		camera: 'Praktica L',
		plenka: 'Kodak Vision 500',
		location: 'Vladivostok, Russky Island',
	},
	{
		id: 10,
		path: '/src/db/photos/photo10.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Arkhangelsk',
	},
	{
		id: 11,
		path: '/src/db/photos/photo11.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Arkhangelsk',
	},
	{
		id: 12,
		path: '/src/db/photos/photo12.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Arkhangelsk',
	},
	{
		id: 13,
		path: '/src/db/photos/photo13.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Arkhangelsk',
	},
	{
		id: 14,
		path: '/src/db/photos/photo14.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Arkhangelsk',
	},
	{
		id: 15,
		path: '/src/db/photos/photo15.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Saint Petersburg',
	},
	{
		id: 16,
		path: '/src/db/photos/photo16.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Saint Petersburg',
	},
	{
		id: 17,
		path: '/src/db/photos/photo17.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Saint Petersburg',
	},
	{
		id: 18,
		path: '/src/db/photos/photo18.jpg',
		camera: 'Praktica L',
		plenka: 'Tasma 100',
		location: 'Saint Petersburg',
	},
];
